export const FETCH_WIKI_ENTRIES = "FETCH_WIKI_ENTRIES";
export const SET_WIKI_ENTRIES = "SET_WIKI_ENTRIES";
export const ADD_WIKI_ENTRY = "ADD_WIKI_ENTRY";
export const MODIFY_WIKI_ENTRY = "MODIFY_WIKI_ENTRY";
