//wikiEnties
export const FETCH_WIKI_ENTRIES = "FETCH_WIKI_ENTRIES";
export const SET_WIKI_ENTRIES = "SET_WIKI_ENTRIES";
export const ADD_WIKI_ENTRY = "ADD_WIKI_ENTRY";
export const MODIFY_WIKI_ENTRY = "MODIFY_WIKI_ENTRY";
export const DELETE_WIKI_ENTRY = "DELETE_WIKI_ENTRY";

//products

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const MODIFY_PRODUCT = "MODIFY_PRODUCT";
export const CHANGE_VISIBILITY = "CHANGE_VISIBILITY";
export const CHANGE_PRICE = "CHANGE_PRICE";

//storage
export const FETCH_STORAGE = "FETCH_STORAGE";
export const SET_STORAGE = "SET_STORAGE";
export const ADD_STORAGE = "ADD_STORAGE";
export const MODIFY_STORAGE = "MODIFY_STORAGE";

//photos
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const DELETE_PHOTO = "DELETE_PHOTO";

//user
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERS = "FETCH_USERS";
export const SET_USER = "SET_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_USER = "UPDATE_USER";

//basket
export const FETCH_BASKET = "FETCH_BASKET";
export const SEND_ITEM_TO_BASKET = "SEND_ITEM_TO_BASKET";
export const SEND_REMOVE_ITEM_FROM_BASKET = "SEND_REMOVE_ITEM_FROM_BASKET";
export const SET_BASKET = "SET_BASKET";
export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET";
export const REMOVE_ITEM_FROM_BASKET = "REMOVE_ITEM_FROM_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";

//order
export const VERIFY_ORDER = "VERIFY_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_USER_ORDERS = "FETCH_USER_ORDERS";
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
export const MAKE_ORDER = "MAKE_ORDER";
export const SET_ORDERS = "SET_ORDERS";
export const SET_BASKET_VERIFIED = "SET_BASKET_VERIFIED";
export const SET_ORDER_COMPLETE = "SET_ORDER_COMPLETE";

//monthlyStatus
export const FETCH_MONTHLY_STATUS = "FETCH_MONTHLY_STATUS";
export const SET_MONTHLY_STATUS = "SET_MONTHLY_STATUS";
